{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "X API v2",
    "description" : "X API v2 available endpoints",
    "termsOfService" : "https://developer.x.com/en/developer-terms/agreement-and-policy.html",
    "contact" : {
      "name" : "X Developers",
      "url" : "https://developer.x.com/"
    },
    "license" : {
      "name" : "X Developer Agreement and Policy",
      "url" : "https://developer.x.com/en/developer-terms/agreement-and-policy.html"
    },
    "version" : "2.150"
  },
  "servers" : [ {
    "url" : "https://api.x.com/2",
    "description" : "X API"
  } ],
  "tags" : [ {
    "name" : "Account Activity",
    "description" : "Endpoints relating to retrieving, managing AAA subscriptions"
  }, {
    "name" : "Bookmarks",
    "description" : "Endpoints related to retrieving, managing bookmarks of a user"
  }, {
    "name" : "Compliance",
    "description" : "Endpoints related to keeping X data in your systems compliant"
  }, {
    "name" : "Connections",
    "description" : "Endpoints related to streaming connections"
  }, {
    "name" : "Direct Messages",
    "description" : "Endpoints related to retrieving, managing Direct Messages"
  }, {
    "name" : "General",
    "description" : "Miscellaneous endpoints for general API functionality"
  }, {
    "name" : "Lists",
    "description" : "Endpoints related to retrieving, managing Lists"
  }, {
    "name" : "Media",
    "description" : "Endpoints related to Media"
  }, {
    "name" : "MediaUpload",
    "description" : "Endpoints related to uploading Media"
  }, {
    "name" : "Spaces",
    "description" : "Endpoints related to retrieving, managing Spaces"
  }, {
    "name" : "Stream",
    "description" : "Endpoints related to streaming"
  }, {
    "name" : "Tweets",
    "description" : "Endpoints related to retrieving, searching, and modifying Tweets"
  }, {
    "name" : "Users",
    "description" : "Endpoints related to retrieving, managing relationships of Users"
  } ],
  "paths" : {
    "/account_activity/replay/webhooks/{webhookId}/subscriptions/all" : {
      "post" : {
        "tags" : [ "Account Activity" ],
        "summary" : "Create replay job",
        "description" : "Creates a replay job to retrieve activities from up to the past 5 days for all subscriptions associated with a given webhook.",
        "operationId" : "createAccountActivityReplayJob",
        "security" : [ {
          "BearerToken" : [ ]
        } ]
      }
    },
    "/account_activity/subscriptions/count" : {
      "get" : {
        "tags" : [ "Account Activity" ],
        "summary" : "Get subscription count",
        "description" : "Retrieves a count of currently active Account Activity subscriptions.",
        "operationId" : "getAccountActivitySubscriptionCount",
        "security" : [ {
          "BearerToken" : [ ]
        } ]
      }
    },
    "/account_activity/webhooks/{webhookId}/subscriptions/all" : {
      "get" : {
        "tags" : [ "Account Activity" ],
        "summary" : "Validate subscription",
        "description" : "Checks a user’s Account Activity subscription for a given webhook.",
        "operationId" : "validateAccountActivitySubscription",
        "security" : [ {
          "OAuth2UserToken" : [ "dm.read", "dm.write", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "Account Activity" ],
        "summary" : "Create subscription",
        "description" : "Creates an Account Activity subscription for the user and the given webhook.",
        "operationId" : "createAccountActivitySubscription",
        "security" : [ {
          "OAuth2UserToken" : [ "dm.read", "dm.write", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/account_activity/webhooks/{webhookId}/subscriptions/all/list" : {
      "get" : {
        "tags" : [ "Account Activity" ],
        "summary" : "Get subscriptions",
        "description" : "Retrieves a list of all active subscriptions for a given webhook.",
        "operationId" : "getAccountActivitySubscriptions",
        "security" : [ {
          "BearerToken" : [ ]
        } ]
      }
    },
    "/account_activity/webhooks/{webhookId}/subscriptions/{userId}/all" : {
      "delete" : {
        "tags" : [ "Account Activity" ],
        "summary" : "Delete subscription",
        "description" : "Deletes an Account Activity subscription for the given webhook and user ID.",
        "operationId" : "deleteAccountActivitySubscription",
        "security" : [ {
          "BearerToken" : [ ]
        } ]
      }
    },
    "/communities/search" : {
      "get" : {
        "tags" : [ "Communities" ],
        "summary" : "Search Communities",
        "description" : "Retrieves a list of Communities matching the specified search query.",
        "operationId" : "searchCommunities",
        "security" : [ {
          "OAuth2UserToken" : [ "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/communities/{id}" : {
      "get" : {
        "tags" : [ "Communities" ],
        "summary" : "Get Community by ID",
        "description" : "Retrieves details of a specific Community by its ID.",
        "operationId" : "getCommunitiesById",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "OAuth2UserToken" : [ "list.read", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/compliance/jobs" : {
      "get" : {
        "tags" : [ "Compliance" ],
        "summary" : "Get Compliance Jobs",
        "description" : "Retrieves a list of Compliance Jobs filtered by job type and optional status.",
        "operationId" : "getComplianceJobs",
        "security" : [ {
          "BearerToken" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "Compliance" ],
        "summary" : "Create Compliance Job",
        "description" : "Creates a new Compliance Job for the specified job type.",
        "operationId" : "createComplianceJobs",
        "security" : [ {
          "BearerToken" : [ ]
        } ]
      }
    },
    "/compliance/jobs/{id}" : {
      "get" : {
        "tags" : [ "Compliance" ],
        "summary" : "Get Compliance Job by ID",
        "description" : "Retrieves details of a specific Compliance Job by its ID.",
        "operationId" : "getComplianceJobsById",
        "security" : [ {
          "BearerToken" : [ ]
        } ]
      }
    },
    "/connections/all" : {
      "delete" : {
        "tags" : [ "Connections" ],
        "summary" : "Terminate all connections",
        "description" : "Terminates all active streaming connections for the authenticated application.",
        "operationId" : "deleteAllConnections",
        "security" : [ {
          "BearerToken" : [ ]
        } ]
      }
    },
    "/dm_conversations" : {
      "post" : {
        "tags" : [ "Direct Messages" ],
        "summary" : "Create DM conversation",
        "description" : "Initiates a new direct message conversation with specified participants.",
        "operationId" : "createDirectMessagesConversation",
        "security" : [ {
          "OAuth2UserToken" : [ "dm.write", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/dm_conversations/with/{participantId}/dm_events" : {
      "get" : {
        "tags" : [ "Direct Messages" ],
        "summary" : "Get DM events for a DM conversation",
        "description" : "Retrieves direct message events for a specific conversation.",
        "operationId" : "getDirectMessagesEventsByParticipantId",
        "security" : [ {
          "OAuth2UserToken" : [ "dm.read", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/dm_conversations/with/{participantId}/messages" : {
      "post" : {
        "tags" : [ "Direct Messages" ],
        "summary" : "Create DM message by participant ID",
        "description" : "Sends a new direct message to a specific participant by their ID.",
        "operationId" : "createDirectMessagesByParticipantId",
        "security" : [ {
          "OAuth2UserToken" : [ "dm.write", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/dm_conversations/{dmConversationId}/messages" : {
      "post" : {
        "tags" : [ "Direct Messages" ],
        "summary" : "Create DM message by conversation ID",
        "description" : "Sends a new direct message to a specific conversation by its ID.",
        "operationId" : "createDirectMessagesByConversationId",
        "security" : [ {
          "OAuth2UserToken" : [ "dm.write", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/dm_conversations/{id}/dm_events" : {
      "get" : {
        "tags" : [ "Direct Messages" ],
        "summary" : "Get DM events for a DM conversation",
        "description" : "Retrieves direct message events for a specific conversation.",
        "operationId" : "getDirectMessagesEventsByConversationId",
        "security" : [ {
          "OAuth2UserToken" : [ "dm.read", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/dm_events" : {
      "get" : {
        "tags" : [ "Direct Messages" ],
        "summary" : "Get DM events",
        "description" : "Retrieves a list of recent direct message events across all conversations.",
        "operationId" : "getDirectMessagesEvents",
        "security" : [ {
          "OAuth2UserToken" : [ "dm.read", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/dm_events/{eventId}" : {
      "get" : {
        "tags" : [ "Direct Messages" ],
        "summary" : "Get DM event by ID",
        "description" : "Retrieves details of a specific direct message event by its ID.",
        "operationId" : "getDirectMessagesEventsById",
        "security" : [ {
          "OAuth2UserToken" : [ "dm.read", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      },
      "delete" : {
        "tags" : [ "Direct Messages" ],
        "summary" : "Delete DM event",
        "description" : "Deletes a specific direct message event by its ID, if owned by the authenticated user.",
        "operationId" : "deleteDirectMessagesEvents",
        "security" : [ {
          "OAuth2UserToken" : [ "dm.read", "dm.write" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/evaluate_note" : {
      "post" : {
        "tags" : [ "Community Notes" ],
        "summary" : "Evaluate a Community Note",
        "description" : "Endpoint to evaluate a community note.",
        "operationId" : "evaluateCommunityNotes",
        "security" : [ {
          "OAuth2UserToken" : [ "tweet.write" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/insights8hr" : {
      "get" : {
        "tags" : [ "Tweets" ],
        "summary" : "Get 28-hour Post insights",
        "description" : "Retrieves engagement metrics for specified Posts over the last 28 hours.",
        "operationId" : "getInsights28Hr",
        "security" : [ {
          "OAuth2UserToken" : [ "tweet.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/insights/historical" : {
      "get" : {
        "tags" : [ "Tweets" ],
        "summary" : "Get historical Post insights",
        "description" : "Retrieves historical engagement metrics for specified Posts within a defined time range.",
        "operationId" : "getInsightsHistorical",
        "security" : [ {
          "OAuth2UserToken" : [ "tweet.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/likes/compliance/stream" : {
      "get" : {
        "tags" : [ "Stream", "Compliance" ],
        "summary" : "Stream Likes compliance data",
        "description" : "Streams all compliance data related to Likes for Users.",
        "operationId" : "streamLikesCompliance",
        "security" : [ {
          "BearerToken" : [ ]
        } ],
        "x-twitter-streaming" : true
      }
    },
    "/likes/firehose/stream" : {
      "get" : {
        "tags" : [ "Stream", "Likes" ],
        "summary" : "Stream all Likes",
        "description" : "Streams all public Likes in real-time.",
        "operationId" : "streamLikesFirehose",
        "security" : [ {
          "BearerToken" : [ ]
        } ],
        "x-twitter-streaming" : true
      }
    },
    "/likes/sample10/stream" : {
      "get" : {
        "tags" : [ "Stream", "Likes" ],
        "summary" : "Stream sampled Likes",
        "description" : "Streams a 10% sample of public Likes in real-time.",
        "operationId" : "streamLikesSample10",
        "security" : [ {
          "BearerToken" : [ ]
        } ],
        "x-twitter-streaming" : true
      }
    },
    "/lists" : {
      "post" : {
        "tags" : [ "Lists" ],
        "summary" : "Create List",
        "description" : "Creates a new List for the authenticated user.",
        "operationId" : "createLists",
        "security" : [ {
          "OAuth2UserToken" : [ "list.read", "list.write", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/lists/{id}" : {
      "get" : {
        "tags" : [ "Lists" ],
        "summary" : "Get List by ID",
        "description" : "Retrieves details of a specific List by its ID.",
        "operationId" : "getListsById",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "OAuth2UserToken" : [ "list.read", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      },
      "put" : {
        "tags" : [ "Lists" ],
        "summary" : "Update List",
        "description" : "Updates the details of a specific List owned by the authenticated user by its ID.",
        "operationId" : "updateLists",
        "security" : [ {
          "OAuth2UserToken" : [ "list.write", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      },
      "delete" : {
        "tags" : [ "Lists" ],
        "summary" : "Delete List",
        "description" : "Deletes a specific List owned by the authenticated user by its ID.",
        "operationId" : "deleteLists",
        "security" : [ {
          "OAuth2UserToken" : [ "list.write", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/lists/{id}/followers" : {
      "get" : {
        "tags" : [ "Lists", "Users" ],
        "summary" : "Get List followers",
        "description" : "Retrieves a list of Users who follow a specific List by its ID.",
        "operationId" : "getListsFollowers",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "OAuth2UserToken" : [ "list.read", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/lists/{id}/members" : {
      "get" : {
        "tags" : [ "Lists", "Users" ],
        "summary" : "Get List members",
        "description" : "Retrieves a list of Users who are members of a specific List by its ID.",
        "operationId" : "getListsMembers",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "OAuth2UserToken" : [ "list.read", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "Lists" ],
        "summary" : "Add List member",
        "description" : "Adds a User to a specific List by its ID.",
        "operationId" : "addListsMember",
        "security" : [ {
          "OAuth2UserToken" : [ "list.write", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/lists/{id}/members/{userId}" : {
      "delete" : {
        "tags" : [ "Lists" ],
        "summary" : "Remove List member",
        "description" : "Removes a User from a specific List by its ID and the User’s ID.",
        "operationId" : "removeListsMemberByUserId",
        "security" : [ {
          "OAuth2UserToken" : [ "list.write", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/lists/{id}/tweets" : {
      "get" : {
        "tags" : [ "Lists", "Tweets" ],
        "summary" : "Get List Posts",
        "description" : "Retrieves a list of Posts associated with a specific List by its ID.",
        "operationId" : "getListsPosts",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "OAuth2UserToken" : [ "list.read", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/media" : {
      "get" : {
        "tags" : [ "Media" ],
        "summary" : "Get Media by media keys",
        "description" : "Retrieves details of Media files by their media keys.",
        "operationId" : "getMediaByMediaKeys",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "OAuth2UserToken" : [ "tweet.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/media/analytics" : {
      "get" : {
        "tags" : [ "Media" ],
        "summary" : "Get Media analytics",
        "description" : "Retrieves analytics data for media.",
        "operationId" : "getMediaAnalytics",
        "security" : [ {
          "OAuth2UserToken" : [ "tweet.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/media/metadata" : {
      "post" : {
        "tags" : [ "Media" ],
        "summary" : "Create Media metadata",
        "description" : "Creates metadata for a Media file.",
        "operationId" : "createMediaMetadata",
        "security" : [ {
          "OAuth2UserToken" : [ "media.write" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/media/subtitles" : {
      "post" : {
        "tags" : [ "Media" ],
        "summary" : "Create Media subtitles",
        "description" : "Creates subtitles for a specific Media file.",
        "operationId" : "createMediaSubtitles",
        "security" : [ {
          "OAuth2UserToken" : [ "media.write" ]
        }, {
          "UserToken" : [ ]
        } ]
      },
      "delete" : {
        "tags" : [ "Media" ],
        "summary" : "Delete Media subtitles",
        "description" : "Deletes subtitles for a specific Media file.",
        "operationId" : "deleteMediaSubtitles",
        "security" : [ {
          "OAuth2UserToken" : [ "media.write" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/media/upload" : {
      "get" : {
        "tags" : [ "Media" ],
        "summary" : "Get Media upload status",
        "description" : "Retrieves the status of a Media upload by its ID.",
        "operationId" : "getMediaUploadStatus",
        "security" : [ {
          "OAuth2UserToken" : [ "media.write" ]
        }, {
          "UserToken" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "Media" ],
        "summary" : "Upload media",
        "description" : "Uploads a media file for use in posts or other content.",
        "operationId" : "mediaUpload",
        "security" : [ {
          "OAuth2UserToken" : [ "media.write" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/media/upload/initialize" : {
      "post" : {
        "tags" : [ "Media" ],
        "summary" : "Initialize media upload",
        "description" : "Initializes a media upload.",
        "operationId" : "initializeMediaUpload",
        "security" : [ {
          "OAuth2UserToken" : [ "media.write" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/media/upload/{id}/append" : {
      "post" : {
        "tags" : [ "Media" ],
        "summary" : "Append Media upload",
        "description" : "Appends data to a Media upload request.",
        "operationId" : "appendMediaUpload",
        "security" : [ {
          "OAuth2UserToken" : [ "media.write" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/media/upload/{id}/finalize" : {
      "post" : {
        "tags" : [ "Media" ],
        "summary" : "Finalize Media upload",
        "description" : "Finalizes a Media upload request.",
        "operationId" : "finalizeMediaUpload",
        "security" : [ {
          "OAuth2UserToken" : [ "media.write" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/media/{mediaKey}" : {
      "get" : {
        "tags" : [ "Media" ],
        "summary" : "Get Media by media key",
        "description" : "Retrieves details of a specific Media file by its media key.",
        "operationId" : "getMediaByMediaKey",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "OAuth2UserToken" : [ "tweet.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/notes" : {
      "post" : {
        "tags" : [ "Community Notes" ],
        "summary" : "Create a Community Note",
        "description" : "Creates a community note endpoint for LLM use case.",
        "operationId" : "createCommunityNotes",
        "security" : [ {
          "OAuth2UserToken" : [ "tweet.write" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/notes/search/notes_written" : {
      "get" : {
        "tags" : [ "Community Notes" ],
        "summary" : "Search for Community Notes Written",
        "description" : "Returns all the community notes written by the user.",
        "operationId" : "searchCommunityNotesWritten",
        "security" : [ {
          "OAuth2UserToken" : [ "tweet.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/notes/search/posts_eligible_for_notes" : {
      "get" : {
        "tags" : [ "Community Notes" ],
        "summary" : "Search for Posts Eligible for Community Notes",
        "description" : "Returns all the posts that are eligible for community notes.",
        "operationId" : "searchEligiblePosts",
        "security" : [ {
          "OAuth2UserToken" : [ "tweet.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/notes/{id}" : {
      "delete" : {
        "tags" : [ "Community Notes" ],
        "summary" : "Delete a Community Note",
        "description" : "Deletes a community note.",
        "operationId" : "deleteCommunityNotes",
        "security" : [ {
          "OAuth2UserToken" : [ "tweet.write" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/openapi.json" : {
      "get" : {
        "tags" : [ "General" ],
        "summary" : "Get OpenAPI Spec.",
        "description" : "Retrieves the full OpenAPI Specification in JSON format. (See https://github.com/OAI/OpenAPI-Specification/blob/master/README.md)",
        "operationId" : "getOpenApiSpec"
      }
    },
    "/spaces" : {
      "get" : {
        "tags" : [ "Spaces" ],
        "summary" : "Get Spaces by IDs",
        "description" : "Retrieves details of multiple Spaces by their IDs.",
        "operationId" : "getSpacesByIds",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "OAuth2UserToken" : [ "space.read", "tweet.read", "users.read" ]
        } ]
      }
    },
    "/spaces/by/creator_ids" : {
      "get" : {
        "tags" : [ "Spaces" ],
        "summary" : "Get Spaces by creator IDs",
        "description" : "Retrieves details of Spaces created by specified User IDs.",
        "operationId" : "getSpacesByCreatorIds",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "OAuth2UserToken" : [ "space.read", "tweet.read", "users.read" ]
        } ]
      }
    },
    "/spaces/search" : {
      "get" : {
        "tags" : [ "Spaces" ],
        "summary" : "Search Spaces",
        "description" : "Retrieves a list of Spaces matching the specified search query.",
        "operationId" : "searchSpaces",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "OAuth2UserToken" : [ "space.read", "tweet.read", "users.read" ]
        } ]
      }
    },
    "/spaces/{id}" : {
      "get" : {
        "tags" : [ "Spaces" ],
        "summary" : "Get space by ID",
        "description" : "Retrieves details of a specific space by its ID.",
        "operationId" : "getSpacesById",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "OAuth2UserToken" : [ "space.read", "tweet.read", "users.read" ]
        } ]
      }
    },
    "/spaces/{id}/buyers" : {
      "get" : {
        "tags" : [ "Spaces", "Tweets" ],
        "summary" : "Get Space ticket buyers",
        "description" : "Retrieves a list of Users who purchased tickets to a specific Space by its ID.",
        "operationId" : "getSpacesBuyers",
        "security" : [ {
          "OAuth2UserToken" : [ "space.read", "tweet.read", "users.read" ]
        } ]
      }
    },
    "/spaces/{id}/tweets" : {
      "get" : {
        "tags" : [ "Spaces", "Tweets" ],
        "summary" : "Get Space Posts",
        "description" : "Retrieves a list of Posts shared in a specific Space by its ID.",
        "operationId" : "getSpacesPosts",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "OAuth2UserToken" : [ "space.read", "tweet.read", "users.read" ]
        } ]
      }
    },
    "/trends/by/woeid/{woeid}" : {
      "get" : {
        "tags" : [ "Trends" ],
        "summary" : "Get Trends by WOEID",
        "description" : "Retrieves trending topics for a specific location identified by its WOEID.",
        "operationId" : "getTrendsByWoeid",
        "security" : [ {
          "BearerToken" : [ ]
        } ]
      }
    },
    "/tweets" : {
      "get" : {
        "tags" : [ "Tweets" ],
        "summary" : "Get Posts by IDs",
        "description" : "Retrieves details of multiple Posts by their IDs.",
        "operationId" : "getPostsByIds",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "OAuth2UserToken" : [ "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "Tweets" ],
        "summary" : "Create Post",
        "description" : "Creates a new Post for the authenticated user.",
        "operationId" : "createPosts",
        "security" : [ {
          "OAuth2UserToken" : [ "tweet.read", "tweet.write", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/tweets/analytics" : {
      "get" : {
        "tags" : [ "Tweets" ],
        "summary" : "Get Post analytics",
        "description" : "Retrieves analytics data for specified Posts within a defined time range.",
        "operationId" : "getPostsAnalytics",
        "security" : [ {
          "OAuth2UserToken" : [ "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/tweets/compliance/stream" : {
      "get" : {
        "tags" : [ "Stream", "Compliance" ],
        "summary" : "Stream Posts compliance data",
        "description" : "Streams all compliance data related to Posts.",
        "operationId" : "streamPostsCompliance",
        "security" : [ {
          "BearerToken" : [ ]
        } ],
        "x-twitter-streaming" : true
      }
    },
    "/tweets/counts/all" : {
      "get" : {
        "tags" : [ "Tweets" ],
        "summary" : "Get count of all Posts",
        "description" : "Retrieves the count of Posts matching a search query from the full archive.",
        "operationId" : "getPostsCountsAll",
        "security" : [ {
          "BearerToken" : [ ]
        } ]
      }
    },
    "/tweets/counts/recent" : {
      "get" : {
        "tags" : [ "Tweets" ],
        "summary" : "Get count of recent Posts",
        "description" : "Retrieves the count of Posts from the last 7 days matching a search query.",
        "operationId" : "getPostsCountsRecent",
        "security" : [ {
          "BearerToken" : [ ]
        } ]
      }
    },
    "/tweets/firehose/stream" : {
      "get" : {
        "tags" : [ "Stream", "Tweets" ],
        "summary" : "Stream all Posts",
        "description" : "Streams all public Posts in real-time.",
        "operationId" : "streamPostsFirehose",
        "security" : [ {
          "BearerToken" : [ ]
        } ],
        "x-twitter-streaming" : true
      }
    },
    "/tweets/firehose/stream/lang/en" : {
      "get" : {
        "tags" : [ "Stream", "Tweets" ],
        "summary" : "Stream English Posts",
        "description" : "Streams all public English-language Posts in real-time.",
        "operationId" : "streamPostsFirehoseEn",
        "security" : [ {
          "BearerToken" : [ ]
        } ],
        "x-twitter-streaming" : true
      }
    },
    "/tweets/firehose/stream/lang/ja" : {
      "get" : {
        "tags" : [ "Stream", "Tweets" ],
        "summary" : "Stream Japanese Posts",
        "description" : "Streams all public Japanese-language Posts in real-time.",
        "operationId" : "streamPostsFirehoseJa",
        "security" : [ {
          "BearerToken" : [ ]
        } ],
        "x-twitter-streaming" : true
      }
    },
    "/tweets/firehose/stream/lang/ko" : {
      "get" : {
        "tags" : [ "Stream", "Tweets" ],
        "summary" : "Stream Korean Posts",
        "description" : "Streams all public Korean-language Posts in real-time.",
        "operationId" : "streamPostsFirehoseKo",
        "security" : [ {
          "BearerToken" : [ ]
        } ],
        "x-twitter-streaming" : true
      }
    },
    "/tweets/firehose/stream/lang/pt" : {
      "get" : {
        "tags" : [ "Stream", "Tweets" ],
        "summary" : "Stream Portuguese Posts",
        "description" : "Streams all public Portuguese-language Posts in real-time.",
        "operationId" : "streamPostsFirehosePt",
        "security" : [ {
          "BearerToken" : [ ]
        } ],
        "x-twitter-streaming" : true
      }
    },
    "/tweets/label/stream" : {
      "get" : {
        "tags" : [ "Stream", "Compliance" ],
        "summary" : "Stream Post labels",
        "description" : "Streams all labeling events applied to Posts.",
        "operationId" : "streamLabelsCompliance",
        "security" : [ {
          "BearerToken" : [ ]
        } ],
        "x-twitter-streaming" : true
      }
    },
    "/tweets/sample/stream" : {
      "get" : {
        "tags" : [ "Stream", "Tweets" ],
        "summary" : "Stream sampled Posts",
        "description" : "Streams a 1% sample of public Posts in real-time.",
        "operationId" : "streamPostsSample",
        "security" : [ {
          "BearerToken" : [ ]
        } ],
        "x-twitter-streaming" : true
      }
    },
    "/tweets/sample10/stream" : {
      "get" : {
        "tags" : [ "Stream", "Tweets" ],
        "summary" : "Stream 10% sampled Posts",
        "description" : "Streams a 10% sample of public Posts in real-time.",
        "operationId" : "streamPostsSample10",
        "security" : [ {
          "BearerToken" : [ ]
        } ],
        "x-twitter-streaming" : true
      }
    },
    "/tweets/search/all" : {
      "get" : {
        "tags" : [ "Tweets" ],
        "summary" : "Search all Posts",
        "description" : "Retrieves Posts from the full archive matching a search query.",
        "operationId" : "searchPostsAll",
        "security" : [ {
          "BearerToken" : [ ]
        } ]
      }
    },
    "/tweets/search/recent" : {
      "get" : {
        "tags" : [ "Tweets" ],
        "summary" : "Search recent Posts",
        "description" : "Retrieves Posts from the last 7 days matching a search query.",
        "operationId" : "searchPostsRecent",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "OAuth2UserToken" : [ "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/tweets/search/stream" : {
      "get" : {
        "tags" : [ "Stream", "Tweets" ],
        "summary" : "Stream filtered Posts",
        "description" : "Streams Posts in real-time matching the active rule set.",
        "operationId" : "streamPosts",
        "security" : [ {
          "BearerToken" : [ ]
        } ],
        "x-twitter-streaming" : true
      }
    },
    "/tweets/search/stream/rules" : {
      "get" : {
        "tags" : [ "Stream", "Tweets" ],
        "summary" : "Get stream rules",
        "description" : "Retrieves the active rule set or a subset of rules for the filtered stream.",
        "operationId" : "getRules",
        "security" : [ {
          "BearerToken" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "Stream", "Tweets" ],
        "summary" : "Update stream rules",
        "description" : "Adds or deletes rules from the active rule set for the filtered stream.",
        "operationId" : "updateRules",
        "security" : [ {
          "BearerToken" : [ ]
        } ]
      }
    },
    "/tweets/search/stream/rules/counts" : {
      "get" : {
        "tags" : [ "Stream", "Tweets" ],
        "summary" : "Get stream rule counts",
        "description" : "Retrieves the count of rules in the active rule set for the filtered stream.",
        "operationId" : "getRuleCounts",
        "security" : [ {
          "BearerToken" : [ ]
        } ]
      }
    },
    "/tweets/search/webhooks" : {
      "get" : {
        "tags" : [ "Webhooks", "Stream" ],
        "summary" : "Get stream links",
        "description" : "Get a list of webhook links associated with a filtered stream ruleset.",
        "operationId" : "getWebhooksStreamLinks",
        "security" : [ {
          "BearerToken" : [ ]
        } ]
      }
    },
    "/tweets/search/webhooks/{webhookId}" : {
      "post" : {
        "tags" : [ "Webhooks", "Stream" ],
        "summary" : "Create stream link",
        "description" : "Creates a link to deliver FilteredStream events to the given webhook.",
        "operationId" : "createWebhooksStreamLink",
        "security" : [ {
          "BearerToken" : [ ]
        } ]
      },
      "delete" : {
        "tags" : [ "Webhooks", "Stream" ],
        "summary" : "Delete stream link",
        "description" : "Deletes a link from FilteredStream events to the given webhook.",
        "operationId" : "deleteWebhooksStreamLink",
        "security" : [ {
          "BearerToken" : [ ]
        } ]
      }
    },
    "/tweets/{id}" : {
      "get" : {
        "tags" : [ "Tweets" ],
        "summary" : "Get Post by ID",
        "description" : "Retrieves details of a specific Post by its ID.",
        "operationId" : "getPostsById",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "OAuth2UserToken" : [ "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      },
      "delete" : {
        "tags" : [ "Tweets" ],
        "summary" : "Delete Post",
        "description" : "Deletes a specific Post by its ID, if owned by the authenticated user.",
        "operationId" : "deletePosts",
        "security" : [ {
          "OAuth2UserToken" : [ "tweet.read", "tweet.write", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/tweets/{id}/liking_users" : {
      "get" : {
        "tags" : [ "Tweets", "Users" ],
        "summary" : "Get Liking Users",
        "description" : "Retrieves a list of Users who liked a specific Post by its ID.",
        "operationId" : "getPostsLikingUsers",
        "security" : [ {
          "OAuth2UserToken" : [ "like.read", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/tweets/{id}/quote_tweets" : {
      "get" : {
        "tags" : [ "Tweets" ],
        "summary" : "Get Quoted Posts",
        "description" : "Retrieves a list of Posts that quote a specific Post by its ID.",
        "operationId" : "getPostsQuotedPosts",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "OAuth2UserToken" : [ "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/tweets/{id}/retweeted_by" : {
      "get" : {
        "tags" : [ "Tweets", "Users" ],
        "summary" : "Get Reposted by",
        "description" : "Retrieves a list of Users who reposted a specific Post by its ID.",
        "operationId" : "getPostsRepostedBy",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "OAuth2UserToken" : [ "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/tweets/{id}/retweets" : {
      "get" : {
        "tags" : [ "Tweets" ],
        "summary" : "Get Reposts",
        "description" : "Retrieves a list of Posts that repost a specific Post by its ID.",
        "operationId" : "getPostsReposts",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "OAuth2UserToken" : [ "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/tweets/{tweetId}/hidden" : {
      "put" : {
        "tags" : [ "Tweets" ],
        "summary" : "Hide reply",
        "description" : "Hides or unhides a reply to a conversation owned by the authenticated user.",
        "operationId" : "hidePostsReply",
        "security" : [ {
          "OAuth2UserToken" : [ "tweet.moderate.write", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/usage/tweets" : {
      "get" : {
        "tags" : [ "Usage" ],
        "summary" : "Get usage",
        "description" : "Retrieves usage statistics for Posts over a specified number of days.",
        "operationId" : "getUsage",
        "security" : [ {
          "BearerToken" : [ ]
        } ]
      }
    },
    "/users" : {
      "get" : {
        "tags" : [ "Users" ],
        "summary" : "Get Users by IDs",
        "description" : "Retrieves details of multiple Users by their IDs.",
        "operationId" : "getUsersByIds",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "OAuth2UserToken" : [ "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/users/by" : {
      "get" : {
        "tags" : [ "Users" ],
        "summary" : "Get Users by usernames",
        "description" : "Retrieves details of multiple Users by their usernames.",
        "operationId" : "getUsersByUsernames",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "OAuth2UserToken" : [ "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/users/by/username/{username}" : {
      "get" : {
        "tags" : [ "Users" ],
        "summary" : "Get User by username",
        "description" : "Retrieves details of a specific User by their username.",
        "operationId" : "getUsersByUsername",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "OAuth2UserToken" : [ "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/users/compliance/stream" : {
      "get" : {
        "tags" : [ "Stream", "Compliance" ],
        "summary" : "Stream Users compliance data",
        "description" : "Streams all compliance data related to Users.",
        "operationId" : "streamUsersCompliance",
        "security" : [ {
          "BearerToken" : [ ]
        } ],
        "x-twitter-streaming" : true
      }
    },
    "/users/me" : {
      "get" : {
        "tags" : [ "Users" ],
        "summary" : "Get my User",
        "description" : "Retrieves details of the authenticated user.",
        "operationId" : "getUsersMe",
        "security" : [ {
          "OAuth2UserToken" : [ "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/users/personalized_trends" : {
      "get" : {
        "tags" : [ "Trends" ],
        "summary" : "Get personalized Trends",
        "description" : "Retrieves personalized trending topics for the authenticated user.",
        "operationId" : "getTrendsPersonalizedTrends",
        "security" : [ {
          "OAuth2UserToken" : [ "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/users/reposts_of_me" : {
      "get" : {
        "tags" : [ "Users" ],
        "summary" : "Get Reposts of me",
        "description" : "Retrieves a list of Posts that repost content from the authenticated user.",
        "operationId" : "getUsersRepostsOfMe",
        "security" : [ {
          "OAuth2UserToken" : [ "timeline.read", "tweet.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/users/search" : {
      "get" : {
        "tags" : [ "Users" ],
        "summary" : "Search Users",
        "description" : "Retrieves a list of Users matching a search query.",
        "operationId" : "searchUsers",
        "security" : [ {
          "OAuth2UserToken" : [ "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/users/{id}" : {
      "get" : {
        "tags" : [ "Users" ],
        "summary" : "Get User by ID",
        "description" : "Retrieves details of a specific User by their ID.",
        "operationId" : "getUsersById",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "OAuth2UserToken" : [ "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/users/{id}/blocking" : {
      "get" : {
        "tags" : [ "Users" ],
        "summary" : "Get blocking",
        "description" : "Retrieves a list of Users blocked by the specified User ID.",
        "operationId" : "getUsersBlocking",
        "security" : [ {
          "OAuth2UserToken" : [ "block.read", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/users/{id}/bookmarks" : {
      "get" : {
        "tags" : [ "Users", "Bookmarks" ],
        "summary" : "Get Bookmarks",
        "description" : "Retrieves a list of Posts bookmarked by the authenticated user.",
        "operationId" : "getUsersBookmarks",
        "security" : [ {
          "OAuth2UserToken" : [ "bookmark.read", "tweet.read", "users.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Users", "Bookmarks" ],
        "summary" : "Create Bookmark",
        "description" : "Adds a post to the authenticated user’s bookmarks.",
        "operationId" : "createUsersBookmark",
        "security" : [ {
          "OAuth2UserToken" : [ "bookmark.write", "tweet.read", "users.read" ]
        } ]
      }
    },
    "/users/{id}/bookmarks/folders" : {
      "get" : {
        "tags" : [ "Users", "Bookmarks" ],
        "summary" : "Get Bookmark folders",
        "description" : "Retrieves a list of Bookmark folders created by the authenticated user.",
        "operationId" : "getUsersBookmarkFolders",
        "security" : [ {
          "OAuth2UserToken" : [ "bookmark.read", "users.read" ]
        } ]
      }
    },
    "/users/{id}/bookmarks/folders/{folderId}" : {
      "get" : {
        "tags" : [ "Users", "Bookmarks" ],
        "summary" : "Get Bookmarks by folder ID",
        "description" : "Retrieves Posts in a specific Bookmark folder by its ID for the authenticated user.",
        "operationId" : "getUsersBookmarksByFolderId",
        "security" : [ {
          "OAuth2UserToken" : [ "bookmark.read", "tweet.read", "users.read" ]
        } ]
      }
    },
    "/users/{id}/bookmarks/{tweetId}" : {
      "delete" : {
        "tags" : [ "Users", "Bookmarks" ],
        "summary" : "Delete Bookmark",
        "description" : "Removes a Post from the authenticated user’s Bookmarks by its ID.",
        "operationId" : "deleteUsersBookmark",
        "security" : [ {
          "OAuth2UserToken" : [ "bookmark.write", "tweet.read", "users.read" ]
        } ]
      }
    },
    "/users/{id}/dm/block" : {
      "post" : {
        "tags" : [ "Users" ],
        "summary" : "Block DMs",
        "description" : "Blocks direct messages to or from a specific User by their ID for the authenticated user.",
        "operationId" : "blockUsersDms",
        "security" : [ {
          "OAuth2UserToken" : [ "dm.write", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/users/{id}/dm/unblock" : {
      "post" : {
        "tags" : [ "Users" ],
        "summary" : "Unblock DMs",
        "description" : "Unblocks direct messages to or from a specific User by their ID for the authenticated user.",
        "operationId" : "unblockUsersDms",
        "security" : [ {
          "OAuth2UserToken" : [ "dm.write", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/users/{id}/followed_lists" : {
      "get" : {
        "tags" : [ "Users", "Lists" ],
        "summary" : "Get followed Lists",
        "description" : "Retrieves a list of Lists followed by a specific User by their ID.",
        "operationId" : "getUsersFollowedLists",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "OAuth2UserToken" : [ "list.read", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "Users", "Lists" ],
        "summary" : "Follow List",
        "description" : "Causes the authenticated user to follow a specific List by its ID.",
        "operationId" : "followList",
        "security" : [ {
          "OAuth2UserToken" : [ "list.write", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/users/{id}/followed_lists/{listId}" : {
      "delete" : {
        "tags" : [ "Users", "Lists" ],
        "summary" : "Unfollow List",
        "description" : "Causes the authenticated user to unfollow a specific List by its ID.",
        "operationId" : "unfollowList",
        "security" : [ {
          "OAuth2UserToken" : [ "list.write", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/users/{id}/followers" : {
      "get" : {
        "tags" : [ "Users" ],
        "summary" : "Get followers",
        "description" : "Retrieves a list of Users who follow a specific User by their ID.",
        "operationId" : "getUsersFollowers",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "OAuth2UserToken" : [ "follows.read", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/users/{id}/following" : {
      "get" : {
        "tags" : [ "Users" ],
        "summary" : "Get following",
        "description" : "Retrieves a list of Users followed by a specific User by their ID.",
        "operationId" : "getUsersFollowing",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "OAuth2UserToken" : [ "follows.read", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "Users" ],
        "summary" : "Follow User",
        "description" : "Causes the authenticated user to follow a specific user by their ID.",
        "operationId" : "followUser",
        "security" : [ {
          "OAuth2UserToken" : [ "follows.write", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/users/{id}/liked_tweets" : {
      "get" : {
        "tags" : [ "Users", "Tweets" ],
        "summary" : "Get liked Posts",
        "description" : "Retrieves a list of Posts liked by a specific User by their ID.",
        "operationId" : "getUsersLikedPosts",
        "security" : [ {
          "OAuth2UserToken" : [ "like.read", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/users/{id}/likes" : {
      "post" : {
        "tags" : [ "Users", "Tweets" ],
        "summary" : "Like Post",
        "description" : "Causes the authenticated user to Like a specific Post by its ID.",
        "operationId" : "likePost",
        "security" : [ {
          "OAuth2UserToken" : [ "like.write", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/users/{id}/likes/{tweetId}" : {
      "delete" : {
        "tags" : [ "Users", "Tweets" ],
        "summary" : "Unlike Post",
        "description" : "Causes the authenticated user to Unlike a specific Post by its ID.",
        "operationId" : "unlikePost",
        "security" : [ {
          "OAuth2UserToken" : [ "like.write", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/users/{id}/list_memberships" : {
      "get" : {
        "tags" : [ "Users", "Lists" ],
        "summary" : "Get List memberships",
        "description" : "Retrieves a list of Lists that a specific User is a member of by their ID.",
        "operationId" : "getUsersListMemberships",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "OAuth2UserToken" : [ "list.read", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/users/{id}/mentions" : {
      "get" : {
        "tags" : [ "Users", "Tweets" ],
        "summary" : "Get mentions",
        "description" : "Retrieves a list of Posts that mention a specific User by their ID.",
        "operationId" : "getUsersMentions",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "OAuth2UserToken" : [ "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/users/{id}/muting" : {
      "get" : {
        "tags" : [ "Users" ],
        "summary" : "Get muting",
        "description" : "Retrieves a list of Users muted by the authenticated user.",
        "operationId" : "getUsersMuting",
        "security" : [ {
          "OAuth2UserToken" : [ "mute.read", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "Users" ],
        "summary" : "Mute User",
        "description" : "Causes the authenticated user to mute a specific User by their ID.",
        "operationId" : "muteUser",
        "security" : [ {
          "OAuth2UserToken" : [ "mute.write", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/users/{id}/owned_lists" : {
      "get" : {
        "tags" : [ "Users", "Lists" ],
        "summary" : "Get owned Lists",
        "description" : "Retrieves a list of Lists owned by a specific User by their ID.",
        "operationId" : "getUsersOwnedLists",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "OAuth2UserToken" : [ "list.read", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/users/{id}/pinned_lists" : {
      "get" : {
        "tags" : [ "Users", "Lists" ],
        "summary" : "Get pinned Lists",
        "description" : "Retrieves a list of Lists pinned by the authenticated user.",
        "operationId" : "getUsersPinnedLists",
        "security" : [ {
          "OAuth2UserToken" : [ "list.read", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "Users", "Lists" ],
        "summary" : "Pin List",
        "description" : "Causes the authenticated user to pin a specific List by its ID.",
        "operationId" : "pinList",
        "security" : [ {
          "OAuth2UserToken" : [ "list.write", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/users/{id}/pinned_lists/{listId}" : {
      "delete" : {
        "tags" : [ "Users", "Lists" ],
        "summary" : "Unpin List",
        "description" : "Causes the authenticated user to unpin a specific List by its ID.",
        "operationId" : "unpinList",
        "security" : [ {
          "OAuth2UserToken" : [ "list.write", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/users/{id}/retweets" : {
      "post" : {
        "tags" : [ "Users", "Tweets" ],
        "summary" : "Repost Post",
        "description" : "Causes the authenticated user to repost a specific Post by its ID.",
        "operationId" : "repostPost",
        "security" : [ {
          "OAuth2UserToken" : [ "tweet.read", "tweet.write", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/users/{id}/retweets/{sourceTweetId}" : {
      "delete" : {
        "tags" : [ "Users", "Tweets" ],
        "summary" : "Unrepost Post",
        "description" : "Causes the authenticated user to unrepost a specific Post by its ID.",
        "operationId" : "unrepostPost",
        "security" : [ {
          "OAuth2UserToken" : [ "tweet.read", "tweet.write", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/users/{id}/timelines/reverse_chronological" : {
      "get" : {
        "tags" : [ "Users", "Tweets" ],
        "summary" : "Get Timeline",
        "description" : "Retrieves a reverse chronological list of Posts in the authenticated User’s Timeline.",
        "operationId" : "getUsersTimeline",
        "security" : [ {
          "OAuth2UserToken" : [ "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/users/{id}/tweets" : {
      "get" : {
        "tags" : [ "Users", "Tweets" ],
        "summary" : "Get Posts",
        "description" : "Retrieves a list of posts authored by a specific User by their ID.",
        "operationId" : "getUsersPosts",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "OAuth2UserToken" : [ "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/users/{sourceUserId}/following/{targetUserId}" : {
      "delete" : {
        "tags" : [ "Users" ],
        "summary" : "Unfollow User",
        "description" : "Causes the authenticated user to unfollow a specific user by their ID.",
        "operationId" : "unfollowUser",
        "security" : [ {
          "OAuth2UserToken" : [ "follows.write", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/users/{sourceUserId}/muting/{targetUserId}" : {
      "delete" : {
        "tags" : [ "Users" ],
        "summary" : "Unmute User",
        "description" : "Causes the authenticated user to unmute a specific user by their ID.",
        "operationId" : "unmuteUser",
        "security" : [ {
          "OAuth2UserToken" : [ "mute.write", "tweet.read", "users.read" ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/webhooks" : {
      "get" : {
        "tags" : [ "Webhooks" ],
        "summary" : "Get webhook",
        "description" : "Get a list of webhook configs associated with a client app.",
        "operationId" : "getWebhooks",
        "security" : [ {
          "BearerToken" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "Webhooks" ],
        "summary" : "Create webhook",
        "description" : "Creates a new webhook configuration.",
        "operationId" : "createWebhooks",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    },
    "/webhooks/{webhookId}" : {
      "put" : {
        "tags" : [ "Webhooks" ],
        "summary" : "Validate webhook",
        "description" : "Triggers a CRC check for a given webhook.",
        "operationId" : "validateWebhooks",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "UserToken" : [ ]
        } ]
      },
      "delete" : {
        "tags" : [ "Webhooks" ],
        "summary" : "Delete webhook",
        "description" : "Deletes an existing webhook configuration.",
        "operationId" : "deleteWebhooks",
        "security" : [ {
          "BearerToken" : [ ]
        }, {
          "UserToken" : [ ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "BearerToken" : {
        "type" : "http",
        "scheme" : "bearer"
      },
      "OAuth2UserToken" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://api.x.com/2/oauth2/authorize",
            "tokenUrl" : "https://api.x.com/2/oauth2/token",
            "scopes" : {
              "block.read" : "View accounts you have blocked.",
              "bookmark.read" : "Read your bookmarked Posts.",
              "bookmark.write" : "Create and delete your bookmarks.",
              "dm.read" : "Read all your Direct Messages.",
              "dm.write" : "Send and manage your Direct Messages.",
              "follows.read" : "View accounts you follow and accounts following you.",
              "follows.write" : "Follow and unfollow accounts on your behalf.",
              "like.read" : "View Posts you have liked and likes you can see.",
              "like.write" : "Like and unlike Posts on your behalf.",
              "list.read" : "View Lists, members, and followers of Lists you created or are a member of, including private Lists.",
              "list.write" : "Create and manage Lists on your behalf.",
              "media.write" : "Upload media, such as photos and videos, on your behalf.",
              "mute.read" : "View accounts you have muted.",
              "mute.write" : "Mute and unmute accounts on your behalf.",
              "offline.access" : "Request a refresh token for the app.",
              "space.read" : "View all Spaces you have access to.",
              "timeline.read" : "View all Custom Timelines you can see, including public Custom Timelines from other developers.",
              "tweet.moderate.write" : "Hide and unhide replies to your Posts.",
              "tweet.read" : "View all Posts you can see, including those from protected accounts.",
              "tweet.write" : "Post and repost on your behalf.",
              "users.read" : "View any account you can see, including protected accounts."
            }
          }
        }
      },
      "UserToken" : {
        "type" : "http",
        "scheme" : "OAuth"
      }
    }
  }
}